spring.application.name=todoapp

server.port=8080
# Set context path
server.servlet.context-path=/
# Disable default error page
server.error.whitelabel.enabled=true  


logging.level.org.springframework=info

management.endpoints.web.exposure.include=health,metrics

# Spring profiles
# spring.profiles.active=prod

# Logging Levels
# trace
# debug
# info
# warning
# error
# off